// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getCatagories.sql

package database

import (
	"context"
)

const getCatagoriesTopic = `-- name: GetCatagoriesTopic :many

SELECT id, category_id, name, slug from Topics 
ORDER BY id
`

func (q *Queries) GetCatagoriesTopic(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, getCatagoriesTopic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMainCategories = `-- name: GetMainCategories :many
SELECT
    id,
    arabicName,
    englishName
FROM MainCatagories
ORDER BY id
`

type GetMainCategoriesRow struct {
	ID          int32
	Arabicname  string
	Englishname string
}

func (q *Queries) GetMainCategories(ctx context.Context) ([]GetMainCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMainCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMainCategoriesRow
	for rows.Next() {
		var i GetMainCategoriesRow
		if err := rows.Scan(&i.ID, &i.Arabicname, &i.Englishname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
