// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getQ.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getRandomQuestionByCriteria = `-- name: GetRandomQuestionByCriteria :one
SELECT 
    q.id, 
    q.q_text, 
    q.answers, 
    q.link, 
    q.level_number,
    t.name AS topic_name, 
    c.arabicName AS category_name
FROM Questions q
JOIN Topics t ON q.topic_id = t.id
JOIN MainCatagories c ON t.category_id = c.id
WHERE c.id = $1 
  AND t.id = $2
  AND q.level_number = $3
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomQuestionByCriteriaParams struct {
	ID          int32
	ID_2        int32
	LevelNumber int32
}

type GetRandomQuestionByCriteriaRow struct {
	ID           int32
	QText        string
	Answers      json.RawMessage
	Link         sql.NullString
	LevelNumber  int32
	TopicName    string
	CategoryName string
}

func (q *Queries) GetRandomQuestionByCriteria(ctx context.Context, arg GetRandomQuestionByCriteriaParams) (GetRandomQuestionByCriteriaRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuestionByCriteria, arg.ID, arg.ID_2, arg.LevelNumber)
	var i GetRandomQuestionByCriteriaRow
	err := row.Scan(
		&i.ID,
		&i.QText,
		&i.Answers,
		&i.Link,
		&i.LevelNumber,
		&i.TopicName,
		&i.CategoryName,
	)
	return i, err
}
