// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getRadios.sql

package database

import (
	"context"
)

const getRadioByID = `-- name: GetRadioByID :one
SELECT id, name, link FROM radios WHERE id = $1
`

func (q *Queries) GetRadioByID(ctx context.Context, id int32) (Radio, error) {
	row := q.db.QueryRowContext(ctx, getRadioByID, id)
	var i Radio
	err := row.Scan(&i.ID, &i.Name, &i.Link)
	return i, err
}

const getRadios = `-- name: GetRadios :many
SELECT id, name, link FROM radios ORDER BY id
`

func (q *Queries) GetRadios(ctx context.Context) ([]Radio, error) {
	rows, err := q.db.QueryContext(ctx, getRadios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Radio
	for rows.Next() {
		var i Radio
		if err := rows.Scan(&i.ID, &i.Name, &i.Link); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
