// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
)

type Maincatagory struct {
	ID          int32
	Arabicname  string
	Englishname string
	Description string
	IconPath    sql.NullString
	CreatedAt   interface{}
	UpdatedAt   interface{}
}

type Question struct {
	ID          int32
	TopicID     int32
	LevelNumber int32
	QText       string
	Answers     json.RawMessage
	Link        sql.NullString
}

type Topic struct {
	ID         int32
	CategoryID int32
	Name       string
	Slug       string
}
