-- +goose Up 

CREATE TABLE MainCatagories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    arabicName TEXT NOT NULL,
    englishName TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_path TEXT DEFAULT '/icons/default.svg',
    created_at TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE MainCatagories;