-- +goose Up 

CREATE TABLE Topics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES MainCatagories(id) ON DELETE CASCADE
);

-- +goose Down 
DROP TABLE Topics;