-- +goose Up

CREATE TABLE Questions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    topic_id INTEGER NOT NULL,
    level_number INTEGER NOT NULL,
    q_text TEXT NOT NULL,
    answers JSON NOT NULL, -- Storing the array here
    link TEXT,
    FOREIGN KEY (topic_id) REFERENCES Topics(id)
);

-- +goose Down

DROP TABLE Questions;